[package]
name = "agb_sound_converter"
version = "0.11.0"
authors = ["Gwilym Kuiper <gw@ilym.me>"]
edition = "2018"
license = "MPL-2.0"
description = "Library for converting wavs for use on the Game Boy Advance"
repository = "https://github.com/agbrs/agb"

[profile.dev]
opt-level = 3
debug = true

[profile.release]
lto = true
debug = true

[lib]
proc-macro = true

[features]
freq18157 = []
freq32768 = []

[dependencies]
hound = "3.4"
syn = "1"
proc-macro2 = "1"
quote = "1"
