version = "1.0"
transparent_colour = "121105"

[image.stars]
filename = "stars.png"
tile_size = "8x8"

[image.title]
filename = "title-screen.png"
tile_size = "8x8"

[image.help]
filename = "help-text.png"
tile_size = "8x8"

[image.descriptions1]
filename = "descriptions1.png"
tile_size = "8x8"

[image.descriptions2]
filename = "descriptions2.png"
tile_size = "8x8"
