[package]
name = "agb_fixnum"
version = "0.2.0"
edition = "2021"
license = "MPL-2.0"
description = "Library for abstracting over fixed precision numbers. Designed for use with the agb library for the Game Boy Advance"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agb_macros = { version = "0.2.0", path = "../agb-macros" }
