[package]
name = "agb"
version = "0.5.0"
authors = ["Corwin Kuiper <corwin@kuiper.dev>"]
edition = "2018"
description = "Library for Game Boy Advance Development"
license = "MPL-2.0"

[profile.dev]
opt-level = 3
debug = true

[profile.release]
lto = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2"

[build-dependencies]
agb_image_converter = { version = "0.4.0", path = "../agb-image-converter" }

[package.metadata.docs.rs]
default-target = "thumbv6m-none-eabi"
targets = []
