[package]
name = "agb"
version = "0.1.1"
authors = ["Corwin Kuiper <corwin@kuiper.dev>"]
edition = "2018"
description = "Library for Game Boy Advance Development"
license = "MPL-2.0"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
panic = "abort"
lto = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.0"

[build-dependencies]
agb_image_converter = { path = "../agb-image-converter" }