[package]
name = "agb_tracker"
version = "0.18.0"
authors = ["Gwilym Inzani <gw@ilym.me>"]
edition = "2021"
license = "MPL-2.0"
description = "Library for playing tracker music. Designed for use with the agb library for the Game Boy Advance."
repository = "https://github.com/agbrs/agb"

[features]
default = ["xm"]
xm = ["dep:agb_xm"]

[dependencies]
agb_xm = { version = "0.18.0", path = "../agb-xm", optional = true }
agb = { version = "0.18.0", path = "../../agb" }
agb_tracker_interop = { version = "0.18.0", path = "../agb-tracker-interop", default-features = false }

[profile.dev]
opt-level = 3
debug = true

[profile.release]
opt-level = 3
lto = "fat"
debug = true

[package.metadata.docs.rs]
default-target = "thumbv4t-none-eabi"
cargo-args = ["-Zbuild-std=core,alloc"]
