[package]
name = "agb_image_converter"
version = "0.1.0"
authors = ["Gwilym Kuiper <gw@ilym.me>"]
edition = "2018"
license = "MPL-2.0"
description = "Library for converting graphics for use on the Game Boy Advance"

[dependencies]
image = { version = "0.23.14", default-features = false, features = [ "png", "bmp" ] }
typed-builder = "0.9.0"