[package]
name = "agb_image_converter"
version = "0.4.0"
authors = ["Gwilym Kuiper <gw@ilym.me>"]
edition = "2018"
license = "MPL-2.0"
description = "Library for converting graphics for use on the Game Boy Advance"

[lib]
proc-macro = true

[dependencies]
image = { version = "0.23.14", default-features = false, features = [ "png", "bmp" ] }
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
syn = "1.0.73"