[package]
name = "pong"
version = "0.1.0"
authors = ["Gwilym Kuiper <gw@ilym.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agb = { version = "0.9.1", path = "../../../agb" }

[profile.release]
panic = "abort"
lto = true