[package]
name = "hyperspace-roll"
version = "0.1.0"
authors = [""]
edition = "2021"

[dependencies]
agb = { version = "0.15.0", path = "../../agb" }

[profile.dev]
opt-level = 3
debug = true
codegen-units = 1

[profile.release]
opt-level = 3
lto = "fat"
debug = true
