[package]
name = "agb_xm_core"
version = "0.16.0"
authors = ["Gwilym Kuiper <gw@ilym.me>"]
edition = "2021"
license = "MPL-2.0"
description = "Library for converting XM tracker files for use with agb-tracker on the Game Boy Advance. You shouldn't use this package directly"
repository = "https://github.com/agbrs/agb"

[dependencies]
proc-macro-error = "1"
proc-macro2 = "1"
quote = "1"
syn = "2"

agb_tracker_interop = { version = "0.16.0", path = "../agb-tracker-interop" }
agb_fixnum = { version = "0.16.0", path = "../../agb-fixnum" }

xmrs = "0.3"