[package]
name = "agb-gbafix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elf = "0.7"
gbafix = "1"
bytemuck = "1"
anyhow = "1"
clap = "4"