[package]
name = "agb-gbafix"
version = "0.16.0"
edition = "2021"
authors = ["Gwilym Inzani <email@gwilym.dev>"]
license = "GPL-3.0"
description = "CLI utility to convert ELF file to valid GBA ROM"
repository = "https://github.com/agbrs/agb"

[dependencies]
elf = "0.7"
gbafix = "1"
bytemuck = "1"
anyhow = "1"
clap = "4"

[profile.dev]
opt-level = 3
debug = true

[profile.release]
opt-level = 3
lto = "fat"
debug = true
