name: Build book

on:
  push:
    branches: [ master ]
    paths:
      'book/**'
  pull_request:
    branches: [ master ]
    paths:
      'book/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Set CARGO_TARGET_DIR
      run: echo "CARGO_TARGET_DIR=$HOME/target" >> $GITHUB_ENV
    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install build-essential binutils-arm-none-eabi libelf-dev zip -y
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v2.1.7
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install mdbook
      run: cargo install mdbook
    - name: Build the book
      run: mdbook build
      working-directory: book