name: Publish sub crate

on:
  push:
    tags:
      - "*/v*"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install build-essential binutils-arm-none-eabi -y
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Login to crates.io
        run: cargo login ${{ secrets.CRATE_API }}
      - name: Publish crate
        run: bash .github/scripts/publish-crate.sh
