name: Publish agb

on:
  push:
    tags:
      - v*


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install build-essential binutils-arm-none-eabi zip -y
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to crates.io
        run: cargo login ${{ secrets.CRATE_API }}
      - name: Publish agb
        run: cargo publish
        working-directory: ./agb

      - name: Update template repo
        env:
          GITHUB_USERNAME: gwilymk
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: bash .github/scripts/update-template-repo.sh

      - name: Install gbafix
        run: cargo install gbafix
      - uses: extractions/setup-just@v1
      - name: Build the examples
        run: just build-roms
      - name: Upload examples to the release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: examples/target/examples.zip
          asset_name: examples.zip
          tag: ${{ github.ref }}
          overwrite: true

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.13'
      - name: Build the book
        run: just build-book
      - name: Deploy the book
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: book/book
